#!/usr/bin/env python3
"""Validate sim/core.f or bundle its explicit repository includes.

This is a source-packaging check, NOT a SystemVerilog compiler. The generated
file still requires a simulator with a separately provided UVM library.
"""

import argparse
from pathlib import Path
import re
import sys

ROOT = Path(__file__).resolve().parents[1]
CORE_SOURCES = (
    "tb/common/matrix_common_pkg.sv",
    "tb/tests/matrix_core_tests_pkg.sv",
    "tb/top/matrix_core_tb.sv",
)
INCLUDE_DIRS = ("tb/common", "tb/tests")
INCLUDE = re.compile(r'^\s*`include\s+"([^"]+)"\s*(?://.*)?$')


class BundleError(ValueError):
    pass


def repository_file(root: Path, path: Path, suffix: str) -> Path:
    resolved = path.resolve()
    if not resolved.is_relative_to(root):
        raise BundleError(f"Source escapes repository: {path}")
    relative = resolved.relative_to(root)
    if relative.parts[:2] not in (("tb", "common"), ("tb", "tests"), ("tb", "top")):
        raise BundleError(f"Source outside formal core: {relative}")
    if resolved.suffix != suffix or not resolved.is_file():
        raise BundleError(f"Missing or invalid {suffix} source: {relative}")
    return resolved


def manifest(root: Path) -> tuple[list[Path], list[Path]]:
    source_names, include_names = [], []
    for original in (root / "sim/core.f").read_text().splitlines():
        line = original.split("//", 1)[0].strip()
        if not line:
            continue
        if line.startswith("+incdir+"):
            include_names.extend(line[len("+incdir+"):].split("+"))
        elif line.startswith(("+", "-")):
            raise BundleError(f"Unsupported manifest directive: {line}")
        else:
            source_names.append(line)
    if tuple(source_names) != CORE_SOURCES or tuple(include_names) != INCLUDE_DIRS:
        raise BundleError("core.f must contain the documented include paths and three sources in order")
    sources = [repository_file(root, root / name, ".sv") for name in source_names]
    directories = [(root / name).resolve() for name in include_names]
    return sources, directories


def bundle(root: Path = ROOT) -> tuple[str, list[str]]:
    root = root.resolve()
    sources, directories = manifest(root)
    used = []

    def expand(path: Path, stack: tuple[Path, ...] = ()) -> str:
        if path in stack:
            raise BundleError(f"Recursive include: {path.relative_to(root)}")
        relative = path.relative_to(root).as_posix()
        if relative not in used:
            used.append(relative)
        result = [f"// BEGIN {relative}\n"]
        for number, line in enumerate(path.read_text().splitlines(keepends=True), 1):
            if not re.match(r"\s*`include\b", line):
                result.append(line)
                continue
            match = INCLUDE.fullmatch(line.rstrip("\r\n"))
            if not match:
                raise BundleError(f"Only literal includes are supported: {relative}:{number}")
            name = match.group(1)
            if name == "uvm_macros.svh":
                result.append(line)  # Provided by the selected simulator/UVM installation.
                continue
            if Path(name).is_absolute() or ".." in Path(name).parts:
                raise BundleError(f"Unsafe include: {relative}:{number}: {name}")
            candidates = [path.parent / name] + [directory / name for directory in directories]
            found = next((candidate for candidate in candidates if candidate.is_file()), None)
            if found is None:
                raise BundleError(f"Unresolved repository include: {relative}:{number}: {name}")
            found = repository_file(root, found, ".svh")
            result.append(expand(found, stack + (path,)))
        result.append(f"\n// END {relative}\n")
        return "".join(result)

    text = "// Generated by scripts/bundle_uvm.py; do not edit.\n"
    text += "// Top: matrix_core_tb. UVM is external. No DUT or lessons are bundled.\n\n"
    text += "\n".join(expand(source) for source in sources)
    if len(re.findall(r"^\s*module\s+matrix_core_tb\b", text, re.MULTILINE)) != 1:
        raise BundleError("Expected exactly one matrix_core_tb module")
    return text, used


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="validate manifest/includes without writing")
    parser.add_argument("--output", default="build/core_bundle.sv", help="output path under build/")
    args = parser.parse_args()
    try:
        content, used = bundle()
        if args.check:
            print(f"SOURCE_CHECK_PASS: {len(used)} formal source files; UVM NOT COMPILED")
        else:
            output = Path(args.output)
            if not output.is_absolute():
                output = ROOT / output
            output = output.resolve()
            if not output.is_relative_to((ROOT / "build").resolve()) or output.suffix != ".sv":
                raise BundleError("Output must be an .sv file under repository build/")
            output.parent.mkdir(parents=True, exist_ok=True)
            output.write_text(content)
            print(f"BUNDLE_READY: {output}; {len(used)} source files; UVM NOT COMPILED")
        return 0
    except (BundleError, OSError) as error:
        print(f"SOURCE_CHECK_FAIL: {error}", file=sys.stderr)
        return 1


if __name__ == "__main__":
    raise SystemExit(main())
